---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
          app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}
      containers:
      - name: {{ .Values.appName }}
        image: fluent/fluent-bit:2.1
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.clusterName }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        ports:
        - containerPort: 2020
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
